# -*- coding: utf-8 -*-
"""text_density_features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btBRE71adoGNmcP0rE3YnT9ZiCs72N-2
"""

# define a function to calculate bounding box manhattan distance
# Manhattan distance
def manhanttan_distance(bbox1, bbox2):
  x1, y1, x12, y12 = bbox1
  x2, y2, x22, y22 = bbox2
  w1 = abs(x12-x1)
  h1 = abs(y12-y1)
  w2 = abs(x22-x2)
  h2 = abs(y22-y2)
  dist = abs(x2-x1) + abs(y2-y1)
  if x2>x1 and abs(x2-x1)>w1:
    dist = dist-w1
  elif x2<x1 and abs(x2-x1)>w2:
    dist = dist-w2
  elif y1>y2 and abs(y1-y2)>h2:
    dist = dist-h2
  elif y2>y1 and abs(y1-y2)>h1:
    dist = dist-h1
  return dist

# directly return the gap distance bewteen bounding boxes
def gap_distance(bbox1, bbox2):
  x1, y1, x12, y12 = bbox1
  x2, y2, x22, y22 = bbox2
  w1 = abs(x12-x1)
  h1 = abs(y12-y1)
  w2 = abs(x22-x2)
  h2 = abs(y22-y2)
  if x2>x1 and abs(x2-x1)>w1:
    dist = abs(x2-x1)-w1
  elif x2<x1 and abs(x2-x1)>w2:
    dist = abs(x2-x1)-w2
  elif y1>y2 and abs(y1-y2)>h2:
    dist = abs(y2-y1)-h2
  elif y2>y1 and abs(y1-y2)>h1:
    dist = abs(y2-y1)-h1
  return dist